services:
  carla:
    image: carlasim/carla:0.9.12
    command: ["sh", "-c", "sleep infinity"]
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d
      - /tmp/.X11-unix:/tmp/.X11-unix
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]

  artery:
    image: ${NEXUS_ADDR}/${ARTERY_IMAGE}:${TAG}
    build:
      dockerfile: artery/Dockerfile
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./cavise/messages:/cavise/messages
      - ./simdata:/cavise/simdata
      - ./artery:/cavise/artery
    command: ["sh", "-c", "sleep infinity"]    
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "artery"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  opencda:
    image: ${NEXUS_ADDR}/${OPENCDA_IMAGE}:${TAG}
    build:
      dockerfile: opencda/Dockerfile
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./cavise/messages:/cavise/messages
      - ./simdata:/cavise/simdata
      - ./.python-version:/cavise/.python-version
      - ./opencda:/cavise/opencda
    command: ["sh", "-c", "sleep infinity"]
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "opencda"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
